{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "d4767cb8",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, render_template, redirect, jsonify\n",
    "\n",
    "import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, inspect, func\n",
    "import json\n",
    "from datetime import datetime\n",
    "from pathlib import Path\n",
    "import pandas as pd\n",
    "\n",
    "import time\n",
    "\n",
    "  \n",
    "# Database Setup\n",
    "connection_string = \"postgres:Golfer7!@localhost:5432/afl_statistics_DB\"\n",
    "engine = create_engine(f'postgresql://{connection_string}')\n",
    "\n",
    "# reflect an existing database into a new model\n",
    "Base = automap_base()\n",
    "\n",
    "# reflect the tables\n",
    "Base.prepare(engine, reflect=True)\n",
    "\n",
    "# Save reference to the table\n",
    "afl_table = Base.classes.afl_team_performance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "444d79f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Sklearn Packages\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "\n",
    "# Sklearn Evaluation Metrics\n",
    "from sklearn import metrics\n",
    "from sklearn.metrics import mean_squared_error, precision_score, confusion_matrix, accuracy_score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "134cd852",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_sql_query('select * from \"afl_team_performance\"',con=engine)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "f9e1a99f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#query = engine.execute('SELECT row_to_json(t) FROM (select country, city, city_latitude, city_longitude, date, duration, state, shape, summary, time from all_countries_ufos) t LIMIT 10000').fetchall()\n",
    "#    query = engine.execute('SELECT row_to_json(usa_ufo) FROM usa_ufo LIMIT 100').fetchall()\n",
    "#my_list = []\n",
    "\n",
    "#for i in range(len(query)):\n",
    "#    my_list.append(query[i][0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "153f9a04",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualizes all the columns\n",
    "pd.set_option('display.max_columns', None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "477a2c0e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>team</th>\n",
       "      <th>gameid</th>\n",
       "      <th>date</th>\n",
       "      <th>year</th>\n",
       "      <th>round</th>\n",
       "      <th>venue</th>\n",
       "      <th>starttime</th>\n",
       "      <th>home_away</th>\n",
       "      <th>team_score</th>\n",
       "      <th>rainfall</th>\n",
       "      <th>team_points</th>\n",
       "      <th>opposing_team</th>\n",
       "      <th>opposing_team_score</th>\n",
       "      <th>win_loss_margin</th>\n",
       "      <th>win_loss_margin_percent</th>\n",
       "      <th>win_loss</th>\n",
       "      <th>disposals</th>\n",
       "      <th>kicks</th>\n",
       "      <th>marks</th>\n",
       "      <th>handballs</th>\n",
       "      <th>goals</th>\n",
       "      <th>behinds</th>\n",
       "      <th>hitouts</th>\n",
       "      <th>tackles</th>\n",
       "      <th>rebounds</th>\n",
       "      <th>inside50s</th>\n",
       "      <th>clearances</th>\n",
       "      <th>clangers</th>\n",
       "      <th>frees</th>\n",
       "      <th>frees_against</th>\n",
       "      <th>contested_possessions</th>\n",
       "      <th>uncontested_possessions</th>\n",
       "      <th>contested_marks</th>\n",
       "      <th>marks_inside50</th>\n",
       "      <th>one_percenters</th>\n",
       "      <th>bounces</th>\n",
       "      <th>goal_assists</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2309</td>\n",
       "      <td>2021-08-22</td>\n",
       "      <td>2021</td>\n",
       "      <td>R23</td>\n",
       "      <td>Adelaide Oval</td>\n",
       "      <td>16:10:00</td>\n",
       "      <td>1</td>\n",
       "      <td>98</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4</td>\n",
       "      <td>North Melbourne</td>\n",
       "      <td>54</td>\n",
       "      <td>44</td>\n",
       "      <td>81.0</td>\n",
       "      <td>1</td>\n",
       "      <td>418</td>\n",
       "      <td>222</td>\n",
       "      <td>90</td>\n",
       "      <td>196</td>\n",
       "      <td>13</td>\n",
       "      <td>17</td>\n",
       "      <td>37</td>\n",
       "      <td>57</td>\n",
       "      <td>28</td>\n",
       "      <td>57</td>\n",
       "      <td>42</td>\n",
       "      <td>55</td>\n",
       "      <td>14</td>\n",
       "      <td>19</td>\n",
       "      <td>152</td>\n",
       "      <td>266</td>\n",
       "      <td>14</td>\n",
       "      <td>22</td>\n",
       "      <td>36</td>\n",
       "      <td>8</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2207</td>\n",
       "      <td>2021-08-15</td>\n",
       "      <td>2021</td>\n",
       "      <td>R22</td>\n",
       "      <td>M.C.G.</td>\n",
       "      <td>14:10:00</td>\n",
       "      <td>0</td>\n",
       "      <td>63</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>104</td>\n",
       "      <td>-41</td>\n",
       "      <td>-65.0</td>\n",
       "      <td>0</td>\n",
       "      <td>386</td>\n",
       "      <td>220</td>\n",
       "      <td>97</td>\n",
       "      <td>166</td>\n",
       "      <td>9</td>\n",
       "      <td>7</td>\n",
       "      <td>28</td>\n",
       "      <td>63</td>\n",
       "      <td>43</td>\n",
       "      <td>47</td>\n",
       "      <td>36</td>\n",
       "      <td>64</td>\n",
       "      <td>18</td>\n",
       "      <td>26</td>\n",
       "      <td>139</td>\n",
       "      <td>244</td>\n",
       "      <td>14</td>\n",
       "      <td>12</td>\n",
       "      <td>38</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2104</td>\n",
       "      <td>2021-08-07</td>\n",
       "      <td>2021</td>\n",
       "      <td>R21</td>\n",
       "      <td>Adelaide Oval</td>\n",
       "      <td>19:10:00</td>\n",
       "      <td>1</td>\n",
       "      <td>51</td>\n",
       "      <td>1.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Port Adelaide</td>\n",
       "      <td>55</td>\n",
       "      <td>-4</td>\n",
       "      <td>-8.0</td>\n",
       "      <td>0</td>\n",
       "      <td>359</td>\n",
       "      <td>205</td>\n",
       "      <td>54</td>\n",
       "      <td>154</td>\n",
       "      <td>7</td>\n",
       "      <td>7</td>\n",
       "      <td>31</td>\n",
       "      <td>64</td>\n",
       "      <td>40</td>\n",
       "      <td>48</td>\n",
       "      <td>33</td>\n",
       "      <td>57</td>\n",
       "      <td>25</td>\n",
       "      <td>23</td>\n",
       "      <td>155</td>\n",
       "      <td>192</td>\n",
       "      <td>8</td>\n",
       "      <td>7</td>\n",
       "      <td>48</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2002</td>\n",
       "      <td>2021-07-31</td>\n",
       "      <td>2021</td>\n",
       "      <td>R20</td>\n",
       "      <td>Eureka Stadium</td>\n",
       "      <td>12:20:00</td>\n",
       "      <td>0</td>\n",
       "      <td>56</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Western Bulldogs</td>\n",
       "      <td>105</td>\n",
       "      <td>-49</td>\n",
       "      <td>-88.0</td>\n",
       "      <td>0</td>\n",
       "      <td>331</td>\n",
       "      <td>185</td>\n",
       "      <td>68</td>\n",
       "      <td>146</td>\n",
       "      <td>8</td>\n",
       "      <td>6</td>\n",
       "      <td>49</td>\n",
       "      <td>59</td>\n",
       "      <td>50</td>\n",
       "      <td>40</td>\n",
       "      <td>35</td>\n",
       "      <td>68</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>143</td>\n",
       "      <td>181</td>\n",
       "      <td>18</td>\n",
       "      <td>8</td>\n",
       "      <td>43</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R1906</td>\n",
       "      <td>2021-07-24</td>\n",
       "      <td>2021</td>\n",
       "      <td>R19</td>\n",
       "      <td>Docklands</td>\n",
       "      <td>19:40:00</td>\n",
       "      <td>1</td>\n",
       "      <td>102</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4</td>\n",
       "      <td>Hawthorn</td>\n",
       "      <td>83</td>\n",
       "      <td>19</td>\n",
       "      <td>23.0</td>\n",
       "      <td>1</td>\n",
       "      <td>353</td>\n",
       "      <td>234</td>\n",
       "      <td>117</td>\n",
       "      <td>119</td>\n",
       "      <td>16</td>\n",
       "      <td>4</td>\n",
       "      <td>29</td>\n",
       "      <td>49</td>\n",
       "      <td>45</td>\n",
       "      <td>48</td>\n",
       "      <td>32</td>\n",
       "      <td>57</td>\n",
       "      <td>23</td>\n",
       "      <td>20</td>\n",
       "      <td>137</td>\n",
       "      <td>210</td>\n",
       "      <td>19</td>\n",
       "      <td>15</td>\n",
       "      <td>50</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       team     gameid        date  year round           venue starttime  \\\n",
       "0  Adelaide  2021R2309  2021-08-22  2021   R23   Adelaide Oval  16:10:00   \n",
       "1  Adelaide  2021R2207  2021-08-15  2021   R22          M.C.G.  14:10:00   \n",
       "2  Adelaide  2021R2104  2021-08-07  2021   R21   Adelaide Oval  19:10:00   \n",
       "3  Adelaide  2021R2002  2021-07-31  2021   R20  Eureka Stadium  12:20:00   \n",
       "4  Adelaide  2021R1906  2021-07-24  2021   R19       Docklands  19:40:00   \n",
       "\n",
       "   home_away  team_score  rainfall  team_points     opposing_team  \\\n",
       "0          1          98       0.0            4   North Melbourne   \n",
       "1          0          63       0.0            0         Melbourne   \n",
       "2          1          51       1.4            0     Port Adelaide   \n",
       "3          0          56       0.2            0  Western Bulldogs   \n",
       "4          1         102       0.0            4          Hawthorn   \n",
       "\n",
       "   opposing_team_score  win_loss_margin  win_loss_margin_percent  win_loss  \\\n",
       "0                   54               44                     81.0         1   \n",
       "1                  104              -41                    -65.0         0   \n",
       "2                   55               -4                     -8.0         0   \n",
       "3                  105              -49                    -88.0         0   \n",
       "4                   83               19                     23.0         1   \n",
       "\n",
       "   disposals  kicks  marks  handballs  goals  behinds  hitouts  tackles  \\\n",
       "0        418    222     90        196     13       17       37       57   \n",
       "1        386    220     97        166      9        7       28       63   \n",
       "2        359    205     54        154      7        7       31       64   \n",
       "3        331    185     68        146      8        6       49       59   \n",
       "4        353    234    117        119     16        4       29       49   \n",
       "\n",
       "   rebounds  inside50s  clearances  clangers  frees  frees_against  \\\n",
       "0        28         57          42        55     14             19   \n",
       "1        43         47          36        64     18             26   \n",
       "2        40         48          33        57     25             23   \n",
       "3        50         40          35        68     20             20   \n",
       "4        45         48          32        57     23             20   \n",
       "\n",
       "   contested_possessions  uncontested_possessions  contested_marks  \\\n",
       "0                    152                      266               14   \n",
       "1                    139                      244               14   \n",
       "2                    155                      192                8   \n",
       "3                    143                      181               18   \n",
       "4                    137                      210               19   \n",
       "\n",
       "   marks_inside50  one_percenters  bounces  goal_assists  \n",
       "0              22              36        8             9  \n",
       "1              12              38        6             6  \n",
       "2               7              48        4             5  \n",
       "3               8              43        4             5  \n",
       "4              15              50        2             9  "
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "a01ad03e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4048\n"
     ]
    }
   ],
   "source": [
    "index = df.index\n",
    "number_of_rows = len(index)\n",
    "print(number_of_rows)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "6b4fb14f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>team</th>\n",
       "      <th>gameid</th>\n",
       "      <th>date</th>\n",
       "      <th>year</th>\n",
       "      <th>round</th>\n",
       "      <th>venue</th>\n",
       "      <th>starttime</th>\n",
       "      <th>home_away</th>\n",
       "      <th>team_score</th>\n",
       "      <th>rainfall</th>\n",
       "      <th>team_points</th>\n",
       "      <th>opposing_team</th>\n",
       "      <th>opposing_team_score</th>\n",
       "      <th>win_loss_margin</th>\n",
       "      <th>win_loss_margin_percent</th>\n",
       "      <th>win_loss</th>\n",
       "      <th>disposals</th>\n",
       "      <th>kicks</th>\n",
       "      <th>marks</th>\n",
       "      <th>handballs</th>\n",
       "      <th>goals</th>\n",
       "      <th>behinds</th>\n",
       "      <th>hitouts</th>\n",
       "      <th>tackles</th>\n",
       "      <th>rebounds</th>\n",
       "      <th>inside50s</th>\n",
       "      <th>clearances</th>\n",
       "      <th>clangers</th>\n",
       "      <th>frees</th>\n",
       "      <th>frees_against</th>\n",
       "      <th>contested_possessions</th>\n",
       "      <th>uncontested_possessions</th>\n",
       "      <th>contested_marks</th>\n",
       "      <th>marks_inside50</th>\n",
       "      <th>one_percenters</th>\n",
       "      <th>bounces</th>\n",
       "      <th>goal_assists</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2309</td>\n",
       "      <td>2021-08-22</td>\n",
       "      <td>2021</td>\n",
       "      <td>R23</td>\n",
       "      <td>Adelaide Oval</td>\n",
       "      <td>16:10:00</td>\n",
       "      <td>1</td>\n",
       "      <td>98</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4</td>\n",
       "      <td>North Melbourne</td>\n",
       "      <td>54</td>\n",
       "      <td>44</td>\n",
       "      <td>81.0</td>\n",
       "      <td>1</td>\n",
       "      <td>418</td>\n",
       "      <td>222</td>\n",
       "      <td>90</td>\n",
       "      <td>196</td>\n",
       "      <td>13</td>\n",
       "      <td>17</td>\n",
       "      <td>37</td>\n",
       "      <td>57</td>\n",
       "      <td>28</td>\n",
       "      <td>57</td>\n",
       "      <td>42</td>\n",
       "      <td>55</td>\n",
       "      <td>14</td>\n",
       "      <td>19</td>\n",
       "      <td>152</td>\n",
       "      <td>266</td>\n",
       "      <td>14</td>\n",
       "      <td>22</td>\n",
       "      <td>36</td>\n",
       "      <td>8</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2207</td>\n",
       "      <td>2021-08-15</td>\n",
       "      <td>2021</td>\n",
       "      <td>R22</td>\n",
       "      <td>M.C.G.</td>\n",
       "      <td>14:10:00</td>\n",
       "      <td>0</td>\n",
       "      <td>63</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "      <td>Melbourne</td>\n",
       "      <td>104</td>\n",
       "      <td>-41</td>\n",
       "      <td>-65.0</td>\n",
       "      <td>0</td>\n",
       "      <td>386</td>\n",
       "      <td>220</td>\n",
       "      <td>97</td>\n",
       "      <td>166</td>\n",
       "      <td>9</td>\n",
       "      <td>7</td>\n",
       "      <td>28</td>\n",
       "      <td>63</td>\n",
       "      <td>43</td>\n",
       "      <td>47</td>\n",
       "      <td>36</td>\n",
       "      <td>64</td>\n",
       "      <td>18</td>\n",
       "      <td>26</td>\n",
       "      <td>139</td>\n",
       "      <td>244</td>\n",
       "      <td>14</td>\n",
       "      <td>12</td>\n",
       "      <td>38</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2104</td>\n",
       "      <td>2021-08-07</td>\n",
       "      <td>2021</td>\n",
       "      <td>R21</td>\n",
       "      <td>Adelaide Oval</td>\n",
       "      <td>19:10:00</td>\n",
       "      <td>1</td>\n",
       "      <td>51</td>\n",
       "      <td>1.4</td>\n",
       "      <td>0</td>\n",
       "      <td>Port Adelaide</td>\n",
       "      <td>55</td>\n",
       "      <td>-4</td>\n",
       "      <td>-8.0</td>\n",
       "      <td>0</td>\n",
       "      <td>359</td>\n",
       "      <td>205</td>\n",
       "      <td>54</td>\n",
       "      <td>154</td>\n",
       "      <td>7</td>\n",
       "      <td>7</td>\n",
       "      <td>31</td>\n",
       "      <td>64</td>\n",
       "      <td>40</td>\n",
       "      <td>48</td>\n",
       "      <td>33</td>\n",
       "      <td>57</td>\n",
       "      <td>25</td>\n",
       "      <td>23</td>\n",
       "      <td>155</td>\n",
       "      <td>192</td>\n",
       "      <td>8</td>\n",
       "      <td>7</td>\n",
       "      <td>48</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R2002</td>\n",
       "      <td>2021-07-31</td>\n",
       "      <td>2021</td>\n",
       "      <td>R20</td>\n",
       "      <td>Eureka Stadium</td>\n",
       "      <td>12:20:00</td>\n",
       "      <td>0</td>\n",
       "      <td>56</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>Western Bulldogs</td>\n",
       "      <td>105</td>\n",
       "      <td>-49</td>\n",
       "      <td>-88.0</td>\n",
       "      <td>0</td>\n",
       "      <td>331</td>\n",
       "      <td>185</td>\n",
       "      <td>68</td>\n",
       "      <td>146</td>\n",
       "      <td>8</td>\n",
       "      <td>6</td>\n",
       "      <td>49</td>\n",
       "      <td>59</td>\n",
       "      <td>50</td>\n",
       "      <td>40</td>\n",
       "      <td>35</td>\n",
       "      <td>68</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>143</td>\n",
       "      <td>181</td>\n",
       "      <td>18</td>\n",
       "      <td>8</td>\n",
       "      <td>43</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Adelaide</td>\n",
       "      <td>2021R1906</td>\n",
       "      <td>2021-07-24</td>\n",
       "      <td>2021</td>\n",
       "      <td>R19</td>\n",
       "      <td>Docklands</td>\n",
       "      <td>19:40:00</td>\n",
       "      <td>1</td>\n",
       "      <td>102</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4</td>\n",
       "      <td>Hawthorn</td>\n",
       "      <td>83</td>\n",
       "      <td>19</td>\n",
       "      <td>23.0</td>\n",
       "      <td>1</td>\n",
       "      <td>353</td>\n",
       "      <td>234</td>\n",
       "      <td>117</td>\n",
       "      <td>119</td>\n",
       "      <td>16</td>\n",
       "      <td>4</td>\n",
       "      <td>29</td>\n",
       "      <td>49</td>\n",
       "      <td>45</td>\n",
       "      <td>48</td>\n",
       "      <td>32</td>\n",
       "      <td>57</td>\n",
       "      <td>23</td>\n",
       "      <td>20</td>\n",
       "      <td>137</td>\n",
       "      <td>210</td>\n",
       "      <td>19</td>\n",
       "      <td>15</td>\n",
       "      <td>50</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       team     gameid        date  year round           venue starttime  \\\n",
       "0  Adelaide  2021R2309  2021-08-22  2021   R23   Adelaide Oval  16:10:00   \n",
       "1  Adelaide  2021R2207  2021-08-15  2021   R22          M.C.G.  14:10:00   \n",
       "2  Adelaide  2021R2104  2021-08-07  2021   R21   Adelaide Oval  19:10:00   \n",
       "3  Adelaide  2021R2002  2021-07-31  2021   R20  Eureka Stadium  12:20:00   \n",
       "4  Adelaide  2021R1906  2021-07-24  2021   R19       Docklands  19:40:00   \n",
       "\n",
       "   home_away  team_score  rainfall  team_points     opposing_team  \\\n",
       "0          1          98       0.0            4   North Melbourne   \n",
       "1          0          63       0.0            0         Melbourne   \n",
       "2          1          51       1.4            0     Port Adelaide   \n",
       "3          0          56       0.2            0  Western Bulldogs   \n",
       "4          1         102       0.0            4          Hawthorn   \n",
       "\n",
       "   opposing_team_score  win_loss_margin  win_loss_margin_percent  win_loss  \\\n",
       "0                   54               44                     81.0         1   \n",
       "1                  104              -41                    -65.0         0   \n",
       "2                   55               -4                     -8.0         0   \n",
       "3                  105              -49                    -88.0         0   \n",
       "4                   83               19                     23.0         1   \n",
       "\n",
       "   disposals  kicks  marks  handballs  goals  behinds  hitouts  tackles  \\\n",
       "0        418    222     90        196     13       17       37       57   \n",
       "1        386    220     97        166      9        7       28       63   \n",
       "2        359    205     54        154      7        7       31       64   \n",
       "3        331    185     68        146      8        6       49       59   \n",
       "4        353    234    117        119     16        4       29       49   \n",
       "\n",
       "   rebounds  inside50s  clearances  clangers  frees  frees_against  \\\n",
       "0        28         57          42        55     14             19   \n",
       "1        43         47          36        64     18             26   \n",
       "2        40         48          33        57     25             23   \n",
       "3        50         40          35        68     20             20   \n",
       "4        45         48          32        57     23             20   \n",
       "\n",
       "   contested_possessions  uncontested_possessions  contested_marks  \\\n",
       "0                    152                      266               14   \n",
       "1                    139                      244               14   \n",
       "2                    155                      192                8   \n",
       "3                    143                      181               18   \n",
       "4                    137                      210               19   \n",
       "\n",
       "   marks_inside50  one_percenters  bounces  goal_assists  \n",
       "0              22              36        8             9  \n",
       "1              12              38        6             6  \n",
       "2               7              48        4             5  \n",
       "3               8              43        4             5  \n",
       "4              15              50        2             9  "
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Drop the null rows\n",
    "df = df.dropna()\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "id": "600ccad0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set features. This will also be used as your x values.\n",
    "features = df.drop(columns=['date','team','venue', 'opposing_team', 'gameid','round','starttime', 'team_score', 'team_points', 'opposing_team_score', 'win_loss_margin', 'win_loss_margin_percent','goals','behinds'])\n",
    "#target = df.win_loss.values.reshape(-1,1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "id": "4bc57b44",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(4048, 23) (4048, 1)\n"
     ]
    }
   ],
   "source": [
    "print(features.shape, target.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "id": "5df3360d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=1, test_size=.40)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 134,
   "id": "822c7c10",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train = features[features['year'] < 2018]\n",
    "X_test = features[features['year'] > 2017]\n",
    "\n",
    "#y_train = X_train.win_loss.values.reshape(-1,1)\n",
    "#y_test = X_test.win_loss.values.reshape(-1,1)\n",
    "y_train = X_train.win_loss.values\n",
    "y_test = X_test.win_loss.values\n",
    "                  \n",
    "X_train = X_train.drop(columns='win_loss')     \n",
    "X_test = X_test.drop(columns='win_loss')    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 135,
   "id": "3b4bdc62",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.61\n",
      "0.39\n"
     ]
    }
   ],
   "source": [
    "# Checking if train test split ran correclty\n",
    "for dataset in [y_train, y_test]:\n",
    "    print(round(len(dataset)/len(target), 2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 136,
   "id": "56867d47",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1566,)"
      ]
     },
     "execution_count": 136,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y_test.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 137,
   "id": "96541ea4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>home_away</th>\n",
       "      <th>rainfall</th>\n",
       "      <th>disposals</th>\n",
       "      <th>kicks</th>\n",
       "      <th>marks</th>\n",
       "      <th>handballs</th>\n",
       "      <th>hitouts</th>\n",
       "      <th>tackles</th>\n",
       "      <th>rebounds</th>\n",
       "      <th>inside50s</th>\n",
       "      <th>clearances</th>\n",
       "      <th>clangers</th>\n",
       "      <th>frees</th>\n",
       "      <th>frees_against</th>\n",
       "      <th>contested_possessions</th>\n",
       "      <th>uncontested_possessions</th>\n",
       "      <th>contested_marks</th>\n",
       "      <th>marks_inside50</th>\n",
       "      <th>one_percenters</th>\n",
       "      <th>bounces</th>\n",
       "      <th>goal_assists</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>83</th>\n",
       "      <td>2017</td>\n",
       "      <td>1</td>\n",
       "      <td>1.4</td>\n",
       "      <td>347</td>\n",
       "      <td>197</td>\n",
       "      <td>92</td>\n",
       "      <td>150</td>\n",
       "      <td>55</td>\n",
       "      <td>70</td>\n",
       "      <td>41</td>\n",
       "      <td>49</td>\n",
       "      <td>39</td>\n",
       "      <td>62</td>\n",
       "      <td>19</td>\n",
       "      <td>24</td>\n",
       "      <td>140</td>\n",
       "      <td>209</td>\n",
       "      <td>10</td>\n",
       "      <td>13</td>\n",
       "      <td>46</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84</th>\n",
       "      <td>2017</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>382</td>\n",
       "      <td>254</td>\n",
       "      <td>135</td>\n",
       "      <td>128</td>\n",
       "      <td>39</td>\n",
       "      <td>64</td>\n",
       "      <td>34</td>\n",
       "      <td>52</td>\n",
       "      <td>42</td>\n",
       "      <td>57</td>\n",
       "      <td>17</td>\n",
       "      <td>23</td>\n",
       "      <td>141</td>\n",
       "      <td>247</td>\n",
       "      <td>9</td>\n",
       "      <td>13</td>\n",
       "      <td>43</td>\n",
       "      <td>9</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85</th>\n",
       "      <td>2017</td>\n",
       "      <td>1</td>\n",
       "      <td>1.8</td>\n",
       "      <td>340</td>\n",
       "      <td>217</td>\n",
       "      <td>77</td>\n",
       "      <td>123</td>\n",
       "      <td>38</td>\n",
       "      <td>88</td>\n",
       "      <td>40</td>\n",
       "      <td>52</td>\n",
       "      <td>42</td>\n",
       "      <td>55</td>\n",
       "      <td>24</td>\n",
       "      <td>19</td>\n",
       "      <td>159</td>\n",
       "      <td>181</td>\n",
       "      <td>10</td>\n",
       "      <td>11</td>\n",
       "      <td>65</td>\n",
       "      <td>2</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>86</th>\n",
       "      <td>2017</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>415</td>\n",
       "      <td>202</td>\n",
       "      <td>87</td>\n",
       "      <td>213</td>\n",
       "      <td>54</td>\n",
       "      <td>62</td>\n",
       "      <td>32</td>\n",
       "      <td>53</td>\n",
       "      <td>50</td>\n",
       "      <td>53</td>\n",
       "      <td>12</td>\n",
       "      <td>23</td>\n",
       "      <td>142</td>\n",
       "      <td>284</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>39</td>\n",
       "      <td>11</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>87</th>\n",
       "      <td>2017</td>\n",
       "      <td>1</td>\n",
       "      <td>3.4</td>\n",
       "      <td>410</td>\n",
       "      <td>232</td>\n",
       "      <td>85</td>\n",
       "      <td>178</td>\n",
       "      <td>53</td>\n",
       "      <td>87</td>\n",
       "      <td>26</td>\n",
       "      <td>63</td>\n",
       "      <td>36</td>\n",
       "      <td>54</td>\n",
       "      <td>28</td>\n",
       "      <td>14</td>\n",
       "      <td>186</td>\n",
       "      <td>231</td>\n",
       "      <td>13</td>\n",
       "      <td>14</td>\n",
       "      <td>60</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    year  home_away  rainfall  disposals  kicks  marks  handballs  hitouts  \\\n",
       "83  2017          1       1.4        347    197     92        150       55   \n",
       "84  2017          1       0.0        382    254    135        128       39   \n",
       "85  2017          1       1.8        340    217     77        123       38   \n",
       "86  2017          0       0.0        415    202     87        213       54   \n",
       "87  2017          1       3.4        410    232     85        178       53   \n",
       "\n",
       "    tackles  rebounds  inside50s  clearances  clangers  frees  frees_against  \\\n",
       "83       70        41         49          39        62     19             24   \n",
       "84       64        34         52          42        57     17             23   \n",
       "85       88        40         52          42        55     24             19   \n",
       "86       62        32         53          50        53     12             23   \n",
       "87       87        26         63          36        54     28             14   \n",
       "\n",
       "    contested_possessions  uncontested_possessions  contested_marks  \\\n",
       "83                    140                      209               10   \n",
       "84                    141                      247                9   \n",
       "85                    159                      181               10   \n",
       "86                    142                      284                5   \n",
       "87                    186                      231               13   \n",
       "\n",
       "    marks_inside50  one_percenters  bounces  goal_assists  \n",
       "83              13              46        6             4  \n",
       "84              13              43        9            11  \n",
       "85              11              65        2             8  \n",
       "86               7              39       11             8  \n",
       "87              14              60        2             9  "
      ]
     },
     "execution_count": 137,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "id": "fbc0ea04",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>home_away</th>\n",
       "      <th>rainfall</th>\n",
       "      <th>disposals</th>\n",
       "      <th>kicks</th>\n",
       "      <th>marks</th>\n",
       "      <th>handballs</th>\n",
       "      <th>hitouts</th>\n",
       "      <th>tackles</th>\n",
       "      <th>rebounds</th>\n",
       "      <th>inside50s</th>\n",
       "      <th>clearances</th>\n",
       "      <th>clangers</th>\n",
       "      <th>frees</th>\n",
       "      <th>frees_against</th>\n",
       "      <th>contested_possessions</th>\n",
       "      <th>uncontested_possessions</th>\n",
       "      <th>contested_marks</th>\n",
       "      <th>marks_inside50</th>\n",
       "      <th>one_percenters</th>\n",
       "      <th>bounces</th>\n",
       "      <th>goal_assists</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>418</td>\n",
       "      <td>222</td>\n",
       "      <td>90</td>\n",
       "      <td>196</td>\n",
       "      <td>37</td>\n",
       "      <td>57</td>\n",
       "      <td>28</td>\n",
       "      <td>57</td>\n",
       "      <td>42</td>\n",
       "      <td>55</td>\n",
       "      <td>14</td>\n",
       "      <td>19</td>\n",
       "      <td>152</td>\n",
       "      <td>266</td>\n",
       "      <td>14</td>\n",
       "      <td>22</td>\n",
       "      <td>36</td>\n",
       "      <td>8</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2021</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>386</td>\n",
       "      <td>220</td>\n",
       "      <td>97</td>\n",
       "      <td>166</td>\n",
       "      <td>28</td>\n",
       "      <td>63</td>\n",
       "      <td>43</td>\n",
       "      <td>47</td>\n",
       "      <td>36</td>\n",
       "      <td>64</td>\n",
       "      <td>18</td>\n",
       "      <td>26</td>\n",
       "      <td>139</td>\n",
       "      <td>244</td>\n",
       "      <td>14</td>\n",
       "      <td>12</td>\n",
       "      <td>38</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>1.4</td>\n",
       "      <td>359</td>\n",
       "      <td>205</td>\n",
       "      <td>54</td>\n",
       "      <td>154</td>\n",
       "      <td>31</td>\n",
       "      <td>64</td>\n",
       "      <td>40</td>\n",
       "      <td>48</td>\n",
       "      <td>33</td>\n",
       "      <td>57</td>\n",
       "      <td>25</td>\n",
       "      <td>23</td>\n",
       "      <td>155</td>\n",
       "      <td>192</td>\n",
       "      <td>8</td>\n",
       "      <td>7</td>\n",
       "      <td>48</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2021</td>\n",
       "      <td>0</td>\n",
       "      <td>0.2</td>\n",
       "      <td>331</td>\n",
       "      <td>185</td>\n",
       "      <td>68</td>\n",
       "      <td>146</td>\n",
       "      <td>49</td>\n",
       "      <td>59</td>\n",
       "      <td>50</td>\n",
       "      <td>40</td>\n",
       "      <td>35</td>\n",
       "      <td>68</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>143</td>\n",
       "      <td>181</td>\n",
       "      <td>18</td>\n",
       "      <td>8</td>\n",
       "      <td>43</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>353</td>\n",
       "      <td>234</td>\n",
       "      <td>117</td>\n",
       "      <td>119</td>\n",
       "      <td>29</td>\n",
       "      <td>49</td>\n",
       "      <td>45</td>\n",
       "      <td>48</td>\n",
       "      <td>32</td>\n",
       "      <td>57</td>\n",
       "      <td>23</td>\n",
       "      <td>20</td>\n",
       "      <td>137</td>\n",
       "      <td>210</td>\n",
       "      <td>19</td>\n",
       "      <td>15</td>\n",
       "      <td>50</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   year  home_away  rainfall  disposals  kicks  marks  handballs  hitouts  \\\n",
       "0  2021          1       0.0        418    222     90        196       37   \n",
       "1  2021          0       0.0        386    220     97        166       28   \n",
       "2  2021          1       1.4        359    205     54        154       31   \n",
       "3  2021          0       0.2        331    185     68        146       49   \n",
       "4  2021          1       0.0        353    234    117        119       29   \n",
       "\n",
       "   tackles  rebounds  inside50s  clearances  clangers  frees  frees_against  \\\n",
       "0       57        28         57          42        55     14             19   \n",
       "1       63        43         47          36        64     18             26   \n",
       "2       64        40         48          33        57     25             23   \n",
       "3       59        50         40          35        68     20             20   \n",
       "4       49        45         48          32        57     23             20   \n",
       "\n",
       "   contested_possessions  uncontested_possessions  contested_marks  \\\n",
       "0                    152                      266               14   \n",
       "1                    139                      244               14   \n",
       "2                    155                      192                8   \n",
       "3                    143                      181               18   \n",
       "4                    137                      210               19   \n",
       "\n",
       "   marks_inside50  one_percenters  bounces  goal_assists  \n",
       "0              22              36        8             9  \n",
       "1              12              38        6             6  \n",
       "2               7              48        4             5  \n",
       "3               8              43        4             5  \n",
       "4              15              50        2             9  "
      ]
     },
     "execution_count": 138,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_test.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0e8f73a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 139,
   "id": "17035492",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Evaluation function\n",
    "\n",
    "def evaluation(y_true, y_pred):\n",
    "    \n",
    "# Print Accuracy, Recall, F1 Score, and Precision metrics.\n",
    "    print('Evaluation Metrics:')\n",
    "    print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred)))\n",
    "    print('Recall: ' + str(metrics.recall_score(y_test, y_pred)))\n",
    "    print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred)))\n",
    "    print('Precision: ' + str(metrics.precision_score(y_test, y_pred)))\n",
    "    \n",
    "# Print Confusion Matrix\n",
    "    print('\\nConfusion Matrix:')\n",
    "    print(' TN,  FP, FN, TP')\n",
    "    print(confusion_matrix(y_true, y_pred).ravel())\n",
    "    \n",
    "# Function Prints best parameters for GridSearchCV\n",
    "def print_results(results):\n",
    "    print('Best Parameters: {}\\n'.format(results.best_params_)) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 141,
   "id": "4691ff6f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Evaluation Metrics:\n",
      "Accuracy: 0.7592592592592593\n",
      "Recall: 0.6422136422136422\n",
      "F1 Score: 0.7258181818181818\n",
      "Precision: 0.8344481605351171\n",
      "\n",
      "Confusion Matrix:\n",
      " TN,  FP, FN, TP\n",
      "[690  99 278 499]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\sampo\\anaconda3\\lib\\site-packages\\sklearn\\linear_model\\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n"
     ]
    }
   ],
   "source": [
    "# Logistic Regression Model\n",
    "lr = LogisticRegression(C=100, max_iter=400, class_weight='balanced')\n",
    "\n",
    "# Fitting Model to the train set\n",
    "lr.fit(X_train, y_train)\n",
    "\n",
    "# Predicting on the test set\n",
    "y_pred = lr.predict(X_test)\n",
    "\n",
    "# Evaluating model\n",
    "evaluation(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca8fc254",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5f7dc8f4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b3160cf9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dcae5f65",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26ef45d9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb26d2e6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e1c59eb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68b07e74",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, render_template, redirect, jsonify\n",
    "\n",
    "import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, inspect, func\n",
    "import json\n",
    "from datetime import datetime\n",
    "from pathlib import Path\n",
    "\n",
    "import time\n",
    "\n",
    "  \n",
    "# Database Setup\n",
    "connection_string = \"postgres:Golfer7!@localhost:5432/ufo_db\"\n",
    "engine = create_engine(f'postgresql://{connection_string}')\n",
    "\n",
    "# reflect an existing database into a new model\n",
    "Base = automap_base()\n",
    "\n",
    "# reflect the tables\n",
    "Base.prepare(engine, reflect=True)\n",
    "\n",
    "# Save reference to the table\n",
    "ufo_table = Base.classes.all_countries_ufos\n",
    "\n",
    "# Flask Routes\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "@app.route(\"/\")\n",
    "def welcome():\n",
    "    return render_template(\"index.html\")\n",
    "\n",
    "\n",
    "\n",
    "@app.route(\"/map\")\n",
    "def map():\n",
    "    # File path setup & transfer of filtered file\n",
    "    from pathlib import Path\n",
    "    src_files_loc = Path(\"/Users/sampo/downloads\")\n",
    "    dest_files_loc = Path(\"./static/Resources\")\n",
    "    print(\"source files: \", src_files_loc)\n",
    "    print(\"dest files: \", dest_files_loc)\n",
    "    for file in src_files_loc.iterdir():\n",
    "        if (file.stem == \"filtered\"): \n",
    "            print(\"found filtered: \",file.stem,\"  suffix: \", file.suffix)\n",
    "            new_file_path = dest_files_loc.joinpath(f\"{file.stem}{file.suffix}\")\n",
    "            print(\"new file path-name: \",new_file_path)\n",
    "            file.replace(new_file_path)\n",
    "\n",
    "\n",
    "    return render_template(\"map.html\")\n",
    "\n",
    "@app.route(\"/charts\")\n",
    "def charts():\n",
    "    # File path setup & transfer of filtered file\n",
    "\n",
    "    return render_template(\"charts.html\")\n",
    "\n",
    "\n",
    "@app.route(\"/movefile\")\n",
    "def movefile():\n",
    "    # File path setup & transfer of filtered file\n",
    "    from pathlib import Path\n",
    "    src_files_loc = Path(\"/Users/sampo/downloads\")\n",
    "    dest_files_loc = Path(\"./static/Resources\")\n",
    "    print(\"source files: \", src_files_loc)\n",
    "    print(\"dest files: \", dest_files_loc)\n",
    "    for file in src_files_loc.iterdir():\n",
    "        if (file.stem == \"filtered\"): \n",
    "            print(\"found filtered: \",file.stem,\"  suffix: \", file.suffix)\n",
    "            new_file_path = dest_files_loc.joinpath(f\"{file.stem}{file.suffix}\")\n",
    "            print(\"new file path-name: \",new_file_path)\n",
    "            file.replace(new_file_path)\n",
    "    return (\"Move done\")\n",
    "\n",
    "@app.route(\"/data\")\n",
    "def data(): \n",
    "\n",
    "    query = engine.execute('SELECT row_to_json(t) FROM (select country, city, city_latitude, city_longitude, date, duration, state, shape, summary, time from all_countries_ufos) t LIMIT 10000').fetchall()\n",
    "#    query = engine.execute('SELECT row_to_json(usa_ufo) FROM usa_ufo LIMIT 100').fetchall()\n",
    "    my_list = []\n",
    "\n",
    "    for i in range(len(query)):\n",
    "        my_list.append(query[i][0])\n",
    "\n",
    "    # Convert query results\n",
    "    # jsonString = json.dumps(my_list)\n",
    "    # jsonFile = open(\"./Resources/data.json\",\"w\")\n",
    "    # jsonFile.write(jsonString)\n",
    "    # jsonFile.close()\n",
    "\n",
    "    return jsonify(my_list)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=True )\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
